In [2]:
import numpy as np

1. What is a Python library? Why ^o we use Python libraries?

A Python library is a collection of pre-written code and functions that extend the capabilities of the Python programming language. These libraries are designed to solve specific problems or provide additional functionality beyond what is available in the core Python language. Python libraries are typically distributed as packages, which can be installed using package managers like pip or conda.

We use Python libraries for several reasons:

1. **Functionality**: Libraries provide ready-to-use functions and classes to perform specific tasks, saving time and effort in writing code from scratch.

2. **Efficiency**: Using pre-written, optimized code from libraries can often lead to more efficient programs compared to writing everything yourself, especially for complex tasks like numerical computation, machine learning, or data analysis.

3. **Community Contribution**: Python has a large and active community of developers who contribute to various libraries. Leveraging these libraries allows us to benefit from the collective expertise of the community.

4. **Standardization**: Libraries often provide standardized solutions to common problems, promoting best practices and making code more maintainable and readable.

5. **Focus on Problem-Solving**: By using libraries, developers can focus more on solving the specific problem at hand rather than reinventing the wheel for common tasks.

Overall, Python libraries enhance the versatility and power of the language, making it suitable for a wide range of applications, from web development to scientific computing.

2. What is the difference between Numpy array an^ List?


NumPy arrays and Python lists are both used to store collections of data, but they have some key differences:

1. **Data Type**: 
   - NumPy arrays are homogeneous, meaning they can only store elements of the same data type. This allows for more efficient storage and operations on large datasets, especially for numerical computations.
   - Python lists can store elements of different data types, making them more flexible but potentially less efficient for numerical computations.

2. **Memory Efficiency**:
   - NumPy arrays are more memory efficient compared to Python lists, especially for large datasets, because they store data in contiguous memory blocks and use fixed-size data types.
   - Python lists are less memory efficient because they store references to objects in memory, which can lead to memory fragmentation and overhead.

3. **Performance**:
   - NumPy arrays offer faster computation and mathematical operations compared to Python lists, especially for large datasets, due to optimized C-level implementations of array operations.
   - Python lists are slower for numerical computations because they are implemented in pure Python and lack the optimizations provided by NumPy.

4. **Functionality**:
   - NumPy arrays offer a wide range of mathematical functions and operations optimized for array computations, such as element-wise operations, linear algebra, Fourier transforms, and random number generation.
   - Python lists provide basic operations like appending, slicing, and iterating, but lack the extensive functionality and optimizations for numerical computations available in NumPy.

5. **Syntax**:
   - NumPy arrays are created using the `np.array()` function and support array-specific operations and methods.
   - Python lists are created using square brackets `[]` and support list-specific operations and methods.

In summary, NumPy arrays are specialized data structures designed for efficient numerical computations, while Python lists are general-purpose data structures with more flexibility but lower performance and efficiency for numerical tasks.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr.size

12

In [18]:
arr.shape

(3, 4)

In [19]:
arr.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [20]:
arr1  = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr1[0]

array([1, 2, 3, 4])

5. How ^o you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [22]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr[2,3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [26]:
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr3[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [38]:
arr = np.random.rand(3,3)

In [39]:
arr

array([[0.93043939, 0.39576103, 0.03117606],
       [0.67387428, 0.94688129, 0.65441744],
       [0.56502608, 0.3482466 , 0.41992245]])

8. Describe the difference between np.random.rand and np.random.randn?

The difference between `np.random.rand` and `np.random.randn` lies in the distribution of the random numbers they generate:

1. **`np.random.rand`**:
   - This function generates random numbers from a uniform distribution over the interval [0, 1).
   - It takes dimensions of the output array as arguments and returns an array of random numbers with those dimensions.
   - Each number generated by `np.random.rand` is independent of the others and has an equal probability of being any value between 0 and 1.

   Example:
   ```python
   np.random.rand(3, 3)
   ```

2. **`np.random.randn`**:
   - This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
   - It takes dimensions of the output array as arguments and returns an array of random numbers with those dimensions.
   - The random numbers generated by `np.random.randn` are not uniformly distributed; rather, they follow a bell-shaped curve centered around 0 with the majority of values falling within 1 standard deviation from the mean.

   Example:
   ```python
   np.random.randn(3, 3)
   ```

In summary, `np.random.rand` generates random numbers from a uniform distribution over [0, 1), while `np.random.randn` generates random numbers from a standard normal distribution with mean 0 and standard deviation 1.

9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
np.expand_dims(arr, axis = 1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [44]:
np.expand_dims(arr, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
1) Index wise multiplication
2) Matix multiplication
3) Add both the matics
4) Subtact matix B from A
5) Divide Matix B by A

In [3]:
matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
matrix2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
print("Index wise multiplication of matrix is : ")
matrix1 * matrix2

Index wise multiplication of matrix is : 


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [21]:
matrix1 + matrix2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [22]:
matrix2 - matrix1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
matrix2/matrix1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function used to swap the byte order of an array is `byteswap()`. This function swaps the byte order of the elements in the array, effectively changing the endianness.


In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap byte order
swapped_arr = arr.byteswap()

print("Original array:", arr)
print("Swapped array:", swapped_arr)

Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The `np.linalg.inv` function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in various areas of linear algebra and numerical computation. Here are some key points regarding its significance:

1. Solving Linear Systems: One of the primary applications of matrix inversion is solving systems of linear equations. Given a system of equations in the form of ( Ax = b \, where ( A ) is a coefficient matrix, ( x ) is the vector of variables to be solved for, and ( b ) is the constant vector, the solution can be found using matrix inversion: ( x = A^{-1}b ).

2. Matrix Equation Solutions: Matrix inversion is essential for solving matrix equations of the form ( AX = B ), where ( A ) and ( B ) are matrices, and ( X ) is the matrix of unknowns. The solution can be expressed as ( X = A^{-1}B ).

3. Eigenvalue and Eigenvector Calculations: In some cases, matrix inversion is involved in computing eigenvalues and eigenvectors. For example, the inverse of ( A - lambda I ), where ( A ) is a matrix, ( lambda ) is an eigenvalue, and ( I ) is the identity matrix, is often used to solve for eigenvectors.

4. Regularization: In numerical computations, especially in regression and optimization problems, regularization techniques are employed to stabilize solutions and prevent overfitting. Matrix inversion is sometimes used in regularization methods like ridge regression and Tikhonov regularization.

5. Pseudo-Inverse: For non-square matrices or matrices that are not invertible, the pseudo-inverse is often used. The pseudo-inverse is closely related to matrix inversion and is computed using techniques such as Singular Value Decomposition (SVD). NumPy's `np.linalg.pinv` function computes the pseudo-inverse.

6. Error Checking: Checking whether a matrix is invertible (i.e., non-singular) is often done by attempting to compute its inverse. If the determinant of the matrix is zero, it is singular and cannot be inverted.

14. What does the np.reshape function do, and how is it used ?

The `np.reshape` function in NumPy is used to change the shape (dimensions) of an array without changing its data. It allows you to reorganize the elements of an array to fit a new shape. The function returns a new array with the specified shape, and if the total number of elements in the original array does not match the number of elements in the new shape, a ValueError is raised.

In the below example, the `np.reshape` function is used to reshape a 1D array `arr1d` into a 2D array `arr2d` with 2 rows and 3 columns.


In [25]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2D array with 2 rows and 3 columns
arr2d = np.reshape(arr1d, (2, 3))

print("Original array (1D):")
print(arr1d)
print("\nReshaped array (2D):")
print(arr2d)

Original array (1D):
[1 2 3 4 5 6]

Reshaped array (2D):
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined together for arithmetic operations. When performing element-wise operations (such as addition, subtraction, multiplication, etc.) on arrays with different shapes, NumPy automatically broadcasts the arrays to have compatible shapes, making the operation possible without the need for explicit loop operations.

Here are the key aspects of broadcasting in NumPy:

1. Implicit Expansion: Broadcasting expands smaller arrays to match the shape of larger arrays, making them compatible for element-wise operations. This expansion is done implicitly without making copies of the data, which improves performance and reduces memory usage.

2. Rules of Broadcasting: NumPy follows a set of rules to determine how arrays with different shapes are broadcasted. The dimensions of the arrays are compared element-wise, starting from the trailing dimensions and working backward. The dimensions are compatible if they are equal or one of them is 1. If the arrays have different numbers of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side.

3. Broadcasting Example: For example, if you have a 2D array of shape `(3, 2)` and a 1D array of shape `(2,)`, NumPy will broadcast the 1D array along the rows to match the shape of the 2D array, effectively duplicating its values along the rows.

4. Performance Benefits: Broadcasting allows for concise and efficient code, as it eliminates the need for explicit looping over array elements. It leverages NumPy's optimized C and Fortran routines to perform operations on large arrays efficiently.

Broadcasting is a fundamental concept in NumPy and is widely used in array manipulation and arithmetic operations. Understanding broadcasting helps in writing more expressive and efficient code when working with multidimensional arrays in NumPy.